language: node_js
sudo: required
node_js:
- 7

before_install:
- wget https://www.kernel.org/pub/software/scm/git/git-2.13.5.tar.gz
- tar -zxf git-2.13.5.tar.gz
- cd git-2.13.5
- make prefix=/usr/local all
- sudo make prefix=/usr/local install
- git version
- openssl aes-256-cbc -K $encrypted_f38ec6afcde3_key -iv $encrypted_f38ec6afcde3_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key
- rvm install ruby --default

install:
- npm install
- npm install gulp -g
- gem install jekyll

script:
- gulp docs-build
- jekyll build --source ./docs --destination ./ghpages

after_success:
- git config --global user.name "Travis CI Test"
- git config --global user.email "test@test.com"
- gulp deploy
# Kill the ssh-agent -> temporary fix for hanging builds
- ssh-agent -k

branches:
  only:
  - v2.0
