language: node_js

node_js:
- 7

before_install:
- openssl aes-256-cbc -K $encrypted_f38ec6afcde3_key -iv $encrypted_f38ec6afcde3_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key

install:
- npm install
- npm install gulp -g
- sudo apt-get install curl
- rvm install ruby --default
- gem install jekyll

script:
- jekyll build --source ./docs --destination ./ghpages

after_success:
- git config --global user.name "Travis CI Test"
- git config --global user.email "test@test.com"
- gulp deploy
# Kill the ssh-agent -> temporary fix for hanging builds
- ssh-agent -k

branches:
  only:
  - v2.0
